### ISSUE TITLE
Subclass views are not preloaded

### ISSUE THREAD

**Issue by pascalbetz** [lotus/view#91] opened 2016-01-09 09:24 UTC
Lotus seems to make a distinction between _Superclass_ and _Subclass_ views. Subclass views are not preloaded like Superclass views are. Here is a gist that explains the details:

https://gist.github.com/pascalbetz/a431457425bef4c6e550

I'm not sure this is a bug. The behavior just is just not the same.

**Comment by jodosha** [comment] 2016-01-14 09:48
@pascalbetz I can't reproduce by following the steps in your gist. **It looks fine to me**.

Here's what I did:

```shell
lotus new bookshelf && cd bookshelf && bundle
bundle exec lotus generate action web books#show
```

Then I added another view:

```ruby
# apps/web/views/books/json_show.rb
require_relative './show'

module Web::Views::Books
  class JsonShow < Show
    format :json
  end
end
```

I added the template:

```erb
# apps/web/templates/books/show.json.erb
{}
```

Started the server with your instructions:

```
➜ RACK_ENV=development puma --threads 4:4 --port 2300 --preload --quiet
Puma starting in single mode...
* Version 2.15.3 (ruby 2.3.0-p0), codename: Autumn Arbor Airbrush
* Min threads: 4, max threads: 4
* Environment: development
Creating registry 70355846399000 for [Web::Views::Books::Show]
Created registry #<Lotus::View::Rendering::Registry:0x007ff9fe770830 @registry={:json=>[Web::Views::Books::JsonShow, #<Lotus::View::Template:0x007ff9fd239368 @_template=#<Tilt::ERBTemplate:0x007ff9fd238ff8 @options={:trim=>"<>"}, @line=1, @file="/Users/luca/Desktop/test/bookshelf/apps/web/templates/books/show.json.erb", @compiled_method={}, @default_encoding=#<Encoding:UTF-8>, @reader=#<Proc:0x007ff9fd238eb8@/Users/luca/.gem/ruby/2.3.0/gems/tilt-2.0.2/lib/tilt/template.rb:78 (lambda)>, @data="{}\n", @outvar="_erbout", @engine=#<ERB:0x007ff9fd238df0 @safe_level=nil, @src="#coding:UTF-8\n_erbout = ''; _erbout.concat \"{}\\n\"\n; _erbout.force_encoding(__ENCODING__)", @encoding=#<Encoding:UTF-8>, @filename=nil, @lineno=0>>>], :all=>[Web::Views::Books::Show, nil], :html=>[Web::Views::Books::Show, #<Lotus::View::Template:0x007ff9fd239f48 @_template=#<Tilt::ERBTemplate:0x007ff9fd239bd8 @options={:trim=>"<>"}, @line=1, @file="/Users/luca/Desktop/test/bookshelf/apps/web/templates/books/show.html.erb", @compiled_method={}, @default_encoding=#<Encoding:UTF-8>, @reader=#<Proc:0x007ff9fd239a98@/Users/luca/.gem/ruby/2.3.0/gems/tilt-2.0.2/lib/tilt/template.rb:78 (lambda)>, @data="", @outvar="_erbout", @engine=#<ERB:0x007ff9fd2399d0 @safe_level=nil, @src="#coding:UTF-8\n_erbout = ''; _erbout.force_encoding(__ENCODING__)", @encoding=#<Encoding:UTF-8>, @filename=nil, @lineno=0>>>]}, @view=Web::Views::Books::Show>
* Listening on tcp://0.0.0.0:2300
Use Ctrl-C to stop
```

Please notice that I have added this line to `Lotus::View::Rendering::Registry#initialize`:

```ruby
        def initialize(*args)
          puts "Creating registry #{ object_id } for #{ args }"
          super
          puts "Created registry #{ self.inspect }"
        end
```

This is why the output is more verbose than your Gist. Now, if you look at `@registry` in that output you'll find both JSON and HTML views referenced:

```
:json=>[Web::Views::Books::JsonShow, #<Lotus::View::Template:0x007ff9fd239368 @_template=#<Tilt::ERBTemplate:0x007ff9fd238ff8 @options={:trim=>"<>"}, @line=1, @file="/Users/luca/Desktop/test/bookshelf/apps/web/templates/books/show.json.erb",
#...
```

```
:html=>[Web::Views::Books::Show, #<Lotus::View::Template:0x007ff9fd239f48 @_template=#<Tilt::ERBTemplate:0x007ff9fd239bd8 @options={:trim=>"<>"}, @line=1, @file="/Users/luca/Desktop/test/bookshelf/apps/web/templates/books/show.html.erb", 
# ...
```

---

Then I hit the server with two requests:

```shell
➜ curl http://0.0.0.0:2300/books/1
```

Which printed:

```shell
resolving with 70355846399000 (Lotus::View::Rendering::Registry)
resolving with 70355835295960 (Lotus::View::Rendering::LayoutRegistry)
```

Then with JSON:

```shell
➜ curl -H "Accept: application/json" http://0.0.0.0:2300/books/1
```

and the output:

```shell
resolving with 70355846399000 (Lotus::View::Rendering::Registry)
resolving with 70355835295960 (Lotus::View::Rendering::LayoutRegistry)
```

---

Closing this. @pascalbetz Please let me know if I'm missing something.

**Closed by jodosha** 2016-01-14 09:48 UTC
