### ISSUE TITLE
Template file is not valid US-ASCII (Encoding::InvalidByteSequenceError)

### ISSUE THREAD

**Issue by rpanachi** [lotus/view#76] opened 2015-08-31 01:15 UTC
The following occurs when I tried to run my test suite on Wercker environment (Docker):

```
/cache/bundle-install/ruby/2.2.0/bundler/gems/lotus-f7d76c295c30/lib/lotus/loader.rb:128:in `module_eval': /pipeline/source/apps/dashboard/templates/layout.html.erb is not valid US-ASCII (Encoding::InvalidByteSequenceError)
    from /cache/bundle-install/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/mapping.rb:136:in `new'
    from /cache/bundle-install/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/mapping.rb:136:in `new'
    from /cache/bundle-install/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt.rb:43:in `new'
    from /cache/bundle-install/ruby/2.2.0/gems/lotus-view-0.4.3/lib/lotus/view/template.rb:10:in `initialize'
    from /cache/bundle-install/ruby/2.2.0/gems/lotus-view-0.4.3/lib/lotus/view/rendering/templates_finder.rb:73:in `new'
    from /cache/bundle-install/ruby/2.2.0/gems/lotus-view-0.4.3/lib/lotus/view/rendering/templates_finder.rb:73:in `block in find'
    from /cache/bundle-install/ruby/2.2.0/gems/lotus-view-0.4.3/lib/lotus/view/rendering/templates_finder.rb:72:in `map'
    from /cache/bundle-install/ruby/2.2.0/gems/lotus-view-0.4.3/lib/lotus/view/rendering/templates_finder.rb:72:in `find'
    from /cache/bundle-install/ruby/2.2.0/gems/lotus-view-0.4.3/lib/lotus/view/rendering/layout_registry.rb:64:in `templates'
    from /cache/bundle-install/ruby/2.2.0/gems/lotus-view-0.4.3/lib/lotus/view/rendering/registry.rb:123:in `template_for'
    from /cache/bundle-install/ruby/2.2.0/gems/lotus-view-0.4.3/lib/lotus/view/rendering/registry.rb:104:in `block in prepare_views!'
```

The template file is in the current encoding:
```shell
$ file -I apps/dashboard/templates/layout.html.erb
apps/dashboard/templates/layout.html.erb: text/html; charset=utf-8
```

I tried to set the `encoding: utf-8` on top of template file, but same error. Tried to set `LC_ALL=en_US.UTF-8` and `LANG=en_US.UTF-8` variables on the environment, but the error persist.

The one way that works is the following monkey patch on my `lib/app.rb`:
```ruby
module Lotus
  module View
    class Template
      def initialize(template)
        @_template = Tilt.new(template, nil, default_encoding: "utf-8")
      end
    end
  end
end
```

Passing the `default_encoding: "utf-8"` to Tilt template works fine. Any idea to bring that encoding config to Lotus::View? Thanks

**Comment by joneslee85** [comment] 2015-09-14 10:00
@rpanachi would you be able to provide us that template file for our investigation?

**Comment by jodosha** [comment] 2015-09-14 10:18
@lotus/core-team I've created a PR to introduce `default_encoding` in `Lotus::View.configure` block.
@rpanachi In order to merge it, we need your template to add it as failing test. Thank you very much.

**Comment by jodosha** [comment] 2015-09-15 12:24
@rpanachi Which Ruby version are you using?

**Comment by rpanachi** [comment] 2015-09-15 17:04
@joneslee85 here a fragment of template that is enough to cause the error:

```
<div id="header" class="col-md-12">
  <div class="container">
    <!-- CONFIGURAÇÃO -->
    <li class="menu-level-1">
      <a href="/configs">Configuração</a>
    </li>
    <!-- / CONFIGURAÇÃO -->
  </div>
</div>  
```

@jodosha I am using ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

@lotus/core-team just confirming, passing the `default_encoding: "utf-8"` option to `Tilt` instance resolved the problem.

Thanks!

**Comment by jodosha** [comment] 2015-09-16 08:06
@rpanachi Thanks for your quick update. I still can't reproduce the error locally or on CI.

Please have a look at this [test](https://github.com/lotus/view/pull/78/files#diff-045e02574f152b6ba6553b330129976dR14). We use your template, **without setting Tilt locale** and it passes.

I've debugged CI env, see this [build](https://travis-ci.org/lotus/view/jobs/80589375).

```shell
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

```shell
$ file --mime test/fixtures/templates/encoding_view.html.erb
test/fixtures/templates/encoding_view.html.erb: text/html; charset=utf-8
```

Is there anything different from your setup? Thank you.

**Comment by joneslee85** [comment] 2015-09-21 10:16
@rpanachi ping

**Comment by rpanachi** [comment] 2015-09-21 12:32
@jodosha My env setup is the same. I checked out the branch `default-encoding` and ran the Wercker build locally, adding this `wercker.yml` on project root:

```yaml
box: ruby:2.2.2
build:
    steps:
        - bundle-install
        - script:
            name: locale
            code: |
              export LANG=en_US.utf8
        - script:
            name: environment information
            code: |
                echo "system: $(uname -a)"
                echo "ruby: $(ruby --version)"
                echo "gems: $(gem list)"
                echo "envs: $(env)"
                echo "locale: $(locale)"
        - script:
               name: test
               code: bundle exec rake test
```

And running `sudo wercker build`, this is the complete output:

```
--> No Docker host specified, checking: unix:///var/run/docker.sock
--> Executing pipeline
--> Running step: setup environment
Pulling from ruby: 2.2.2
Already exists: 902b87aaaec9
Already exists: 9a61b6b1315e
Already exists: 1ff9f26f09fb
Already exists: 607e965985c1
Already exists: 9213e81cb0f2
Already exists: 68e6b69220e6
Already exists: 98d9b550773a
Already exists: a6f910a70a8b
Already exists: 70aaa32bac74
Already exists: 328b8d8d5f29
Already exists: 6cc6e6b9897f
Already exists: a258a6d11ba6
Already exists: 6c2bd65ee48c
Already exists: 3c6f42a203cc
Already exists: 0d7c46794474
Already exists: dfb63f893158
Already exists: 9664620d4c2a
Digest: sha256:76059222ec07aa8b9dc6fe2ff097a359ded336c98c664911bb3bd6545604ad5f
Status: Image is up to date for ruby:2.2.2
--> Running step: wercker-init
--> Running step: bundle-install
Gemfile found. Start bundle install.
bundler gem is available, and will not be installed by this step
type bundle: bundle is /usr/local/bundle/bin/bundle
bundle version: Bundler version 1.10.6
bundle install --path /cache/bundle-install/
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching git://github.com/lotus/utils.git
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using bundler 1.10.6
Installing byebug 6.0.2 with native extensions
Installing json 1.8.3 with native extensions
Installing unf_ext 0.0.7.1 with native extensions
Installing unf 0.1.4
Installing domain_name 0.5.24
Installing http-cookie 1.0.2
Installing mime-types 2.6.2
Installing netrc 0.10.3
Installing rest-client 1.8.0
Installing docile 1.1.5
Installing simplecov-html 0.10.0
Installing simplecov 0.10.0
Installing tins 1.6.0
Installing term-ansicolor 1.3.2
Installing thor 0.19.1
Installing coveralls 0.8.2
Installing tilt 2.0.1
Installing haml 4.0.7
Using lotus-utils 0.5.2 from git://github.com/lotus/utils.git (at 0.5.x)
Using lotus-view 0.4.3 from source at .
Installing minitest 5.8.0
Installing yard 0.8.7.6
Bundle complete! 10 Gemfile dependencies, 24 gems now installed.
Bundled gems are installed into /cache/bundle-install.
Post-install message from haml:

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

finished bundle install --path /cache/bundle-install/
skipping rbenv rehash because rbenv is not found
--> Running step: locale
--> Running step: environment information
system: Linux e83397f1f971 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
ruby: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
gems: bigdecimal (1.2.6)
bundler (1.10.6)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
rubygems-update (2.4.8)
test-unit (3.0.8)
envs: WERCKER_BUNDLE_INSTALL_VERSION=>=1.5.2
HOSTNAME=e83397f1f971
GEM_HOME=/usr/local/bundle
TERM=xterm-256color
WERCKER=true
WERCKER_APPLICATION_OWNER_NAME=root
WERCKER_APPLICATION_NAME=lotus-view
OLDPWD=/pipeline/source
WERCKER_CACHE_DIR=/cache
WERCKER_GIT_DOMAIN=
WERCKER_STEP_OWNER=wercker
WERCKER_GIT_BRANCH=default-encoding
WERCKER_SOURCE_DIR=/pipeline/source
WERCKER_BUILD_ID=b992b89b-ad32-4f13-8c47-4dac340c9941
WERCKER_REPORT_NUMBERS_FILE=/report/script-123d81db-90a5-41e1-b123-97876f56725e/numbers.ini
WERCKER_REPORT_DIR=/pipeline/report
WERCKER_STEP_NAME=script
WERCKER_GIT_COMMIT=af284d3f130671cd51c1e66c304c8be7119f5cee
BUNDLE_APP_CONFIG=/usr/local/bundle
WERCKER_REPORT_ARTIFACTS_DIR=/report/script-123d81db-90a5-41e1-b123-97876f56725e/artifacts
WERCKER_REPORT_MESSAGE_FILE=/report/script-123d81db-90a5-41e1-b123-97876f56725e/message.txt
WERCKER_GIT_REPOSITORY=
PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUBY_DOWNLOAD_SHA256=5ffc0f317e429e6b29d4a98ac521c3ce65481bfd22a8cf845fa02a7b113d9b44
BUILD=true
WERCKER_APPLICATION_URL=https://app.wercker.com/#application/lotus-view
PWD=/pipeline/source
LANG=en_US.utf8
WERCKER_ROOT=/pipeline/source
WERCKER_STEP_ROOT=/pipeline/script-123d81db-90a5-41e1-b123-97876f56725e
RUBY_MAJOR=2.2
RUBYGEMS_VERSION=2.4.8
WERCKER_PIPELINE_DIR=/pipeline
WERCKER_OUTPUT_DIR=/pipeline/output
SHLVL=1
HOME=/root
WERCKER_BUILD_URL=https://app.wercker.com/#build/b992b89b-ad32-4f13-8c47-4dac340c9941
WERCKER_APPLICATION_ID=lotus-view
CI=true
WERCKER_GIT_OWNER=root
WERCKER_STEP_ID=script-123d81db-90a5-41e1-b123-97876f56725e
RUBY_VERSION=2.2.2
BUNDLER_VERSION=1.10.6
locale: LANG=en_US.utf8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
--> Running step: test
/cache/bundle-install/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:83:in `initialize': /pipeline/source/test/fixtures/templates/encoding_view.html.erb is not valid US-ASCII (Encoding::InvalidByteSequenceError)
	from /cache/bundle-install/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/mapping.rb:136:in `new'
	from /cache/bundle-install/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/mapping.rb:136:in `new'
	from /cache/bundle-install/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt.rb:43:in `new'
	from /pipeline/source/lib/lotus/view/template.rb:10:in `initialize'
	from /pipeline/source/lib/lotus/view/rendering/templates_finder.rb:73:in `new'
	from /pipeline/source/lib/lotus/view/rendering/templates_finder.rb:73:in `block in find'
	from /pipeline/source/lib/lotus/view/rendering/templates_finder.rb:72:in `map'
	from /pipeline/source/lib/lotus/view/rendering/templates_finder.rb:72:in `find'
	from /pipeline/source/lib/lotus/view/rendering/layout_registry.rb:64:in `templates'
	from /pipeline/source/lib/lotus/view/rendering/registry.rb:123:in `template_for'
	from /pipeline/source/lib/lotus/view/rendering/registry.rb:104:in `block in prepare_views!'
	from /usr/local/lib/ruby/2.2.0/set.rb:283:in `each_key'
	from /usr/local/lib/ruby/2.2.0/set.rb:283:in `each'
	from /pipeline/source/lib/lotus/view/rendering/registry.rb:103:in `prepare_views!'
	from /pipeline/source/lib/lotus/view/rendering/registry.rb:98:in `prepare!'
	from /pipeline/source/lib/lotus/view/rendering/layout_registry.rb:34:in `initialize'
	from /pipeline/source/lib/lotus/view/rendering.rb:261:in `new'
	from /pipeline/source/lib/lotus/view/rendering.rb:261:in `registry'
	from /pipeline/source/lib/lotus/view/rendering.rb:249:in `load!'
	from /pipeline/source/lib/lotus/view/configuration.rb:378:in `block in load!'
	from /usr/local/lib/ruby/2.2.0/set.rb:283:in `each_key'
	from /usr/local/lib/ruby/2.2.0/set.rb:283:in `each'
	from /pipeline/source/lib/lotus/view/configuration.rb:378:in `load!'
	from /pipeline/source/lib/lotus/view.rb:290:in `load!'
	from /pipeline/source/test/test_helper.rb:35:in `<top (required)>'
	from /pipeline/source/test/escape_test.rb:1:in `require'
	from /pipeline/source/test/escape_test.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `require'
	from /usr/local/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /usr/local/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `each'
	from /usr/local/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `block in <main>'
	from /usr/local/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
	from /usr/local/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/usr/local/lib/ruby/2.2.0" "/usr/local/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/*_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
--> Step failed: test
--> Pipeline failed
WARNING Box container has already stopped.
```

**My final thoughts**: since this problem only happens in the Wercker environment, it should be a bug on Docker build image used by Wercker.

Since this a tiny change, please consider merging to project. Thanks!

**Comment by joneslee85** [comment] 2015-10-14 11:18
ping @jodosha, time to get merge or close

**Comment by jodosha** [comment] 2015-10-16 10:24
@rpanachi @joneslee85 merged :+1:

**Closed** 2015-10-16 10:23 UTC
Labels: bug, discussion
